# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "boot_command_prefix" {
  type    = string
  default = "<enter><wait><f6><esc><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>"
}

variable "cleanup_pause" {
  type    = string
  default = ""
}

variable "cpus" {
  type    = string
  default = "1"
}

variable "desktop" {
  type    = string
  default = "false"
}

variable "disk_size" {
  type    = string
  default = "65536"
}

variable "headless" {
  type    = string
  default = "true"
}

variable "hostname" {
  type    = string
  default = "vagrant"
}

variable "iso_checksum" {
  type = string
}

variable "iso_checksum_type" {
  type = string
}

variable "iso_url" {
  type = string
}

variable "install_dev_packages" {
  type    = string
  default = "false"
}

variable "install_vagrant_key" {
  type    = string
  default = "true"
}

variable "locale" {
  type    = string
  default = "en_US"
}

variable "memory" {
  type    = string
  default = "512"
}

variable "no_proxy" {
  type    = string
  default = "${env("no_proxy")}"
}

variable "preseed" {
  type    = string
  default = "preseed.cfg"
}

variable "rsync_proxy" {
  type    = string
  default = "${env("rsync_proxy")}"
}

variable "ssh_fullname" {
  type    = string
  default = "vagrant"
}

variable "ssh_password" {
  type    = string
  default = "vagrant"
}

variable "ssh_username" {
  type    = string
  default = "vagrant"
}

variable "vm_name" {
  type    = string
  default = "ubuntu-18.04"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "qemu" "ubuntu" {
  boot_command     = ["${var.boot_command_prefix}", "/install/vmlinuz noapic ", "file=/floppy/${var.preseed} ", "debian-installer=${var.locale} auto locale=${var.locale} kbd-chooser/method=us ", "hostname=${var.hostname} ", "fb=false debconf/frontend=noninteractive ", "keyboard-configuration/modelcode=SKIP ", "keyboard-configuration/layout=USA ", "keyboard-configuration/variant=USA console-setup/ask_detect=false ", "passwd/user-fullname=${var.ssh_fullname} ", "passwd/user-password=${var.ssh_password} ", "passwd/user-password-again=${var.ssh_password} ", "passwd/username=${var.ssh_username} ", "initrd=/install/initrd.gz -- <enter>"]
  cpus             = "${var.cpus}"
  disk_interface   = "ide"
  disk_size        = "${var.disk_size}"
  floppy_files     = ["http/${var.preseed}"]
  format           = "qcow2"
  headless         = "${var.headless}"
  http_directory   = "http"
  iso_checksum     = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  memory           = "${var.memory}"
  output_directory = "output-qemu"
  shutdown_command = "echo '${var.ssh_password}'| sudo -S shutdown -P now"
  ssh_password     = "${var.ssh_password}"
  ssh_timeout      = "10000s"
  ssh_username     = "${var.ssh_username}"
  vm_name          = "${var.vm_name}.qcow2"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.qemu.ubuntu"]

  provisioner "ansible" {
    playbook_file = "playbook.yml"
    user = "${var.ssh_username}"
    use_proxy = false
    extra_arguments = ["-vvvvvvvvvvv"]
  }
}
